apiVersion: v1
kind: Service
metadata:
  name: whatisdockerservice
spec:
  selector:
    app: whatisdocker
    tier: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: rails
  type: LoadBalancer
