apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: whatisdocker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: whatisdocker
        tier: backend
        track: stabel
    spec:
      containers:
        - name: whatisdockercontainer
          image: whatisdocker
          ports:
            - name: rails
              containerPort: 8080
          env:
            - name: spring_profile_active
              value: test