apiVersion: v1
kind: Service
metadata:
  name: jwtworkservice
spec:
  selector:
    app: jwtworkappname
    tier: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
